package com.loan_org.notification_service.domain.audit;

import com.loan_org.notification_service.shared.model.NotificationStatus;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.mongodb.repository.MongoRepository;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Spring Data MongoDB repository infrastructure supplying direct data access,
 * mutation routines, and optimized lookup pipelines for {@link NotificationLogDocument} assets.
 *
 * @author amanfoundongithub
 * @version 1.0.0
 */
public interface NotificationLogRepository extends MongoRepository<NotificationLogDocument, String> {

    /**
     * Retrieves a paginated slice of notification logs mapped to a specific client account.
     * Backed efficiently by the compound index 'idx_user_created_at'.
     *
     * @param userId   The targeted domain identity profile string
     * @param pageable Sorting and size window parameters passed down by the API layer
     * @return A slice view page containing filtered historical log assets
     */
    Page<NotificationLogDocument> findByUserId(String userId, Pageable pageable);

    /**
     * Locates all pending logs whose retry metrics match an eligible recovery execution window.
     * Backed efficiently by the compound index 'idx_status_next_retry'.
     *
     * @param status The targeted operational lifecycle state (typically NotificationStatus.RETRYING)
     * @param time   The cut-off threshold timestamp calculation boundary (typically Instant.now())
     * @return A collection list of transiently failed documents eligible for re-dispatch processing
     */
    List<NotificationLogDocument> findByStatusAndNextRetryAtBefore(NotificationStatus status, Instant time);

    /**
     * Resolves a logged communication log tracing ticket back using the receipt confirmation hash
     * issued natively by third-party delivery gateways.
     *
     * @param providerReferenceId Unique tracking token issued by external relays (e.g., SendGrid, Twilio)
     * @return An Optional wrapper containing the matched audit document if found
     */
    Optional<NotificationLogDocument> findByProviderReferenceId(String providerReferenceId);

    /**
     * Resolves an execution audit record by tracking its upstream originating operational correlation hash.
     *
     * @param transactionId Distributed correlation tracer token generated by ingress API boundaries
     * @return An Optional wrapper containing the matched audit document if found
     */
    Optional<NotificationLogDocument> findByTransactionId(String transactionId);

}
