plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.loan_org'
version = 'Notification-Service-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Core Spring Starters
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-amqp'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'net.logstash.logback:logstash-logback-encoder:9.0'
    implementation 'org.jsoup:jsoup:1.17.2'

    compileOnly "org.jspecify:jspecify:1.0.0"

    // JWT library
    implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
    runtimeOnly    'io.jsonwebtoken:jjwt-impl:0.13.0'
    runtimeOnly    'io.jsonwebtoken:jjwt-jackson:0.13.0'


    // Lombok Core
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing Suite (Cleaned up to prevent configuration hijacking)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.amqp:spring-rabbit-test'

    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}