spring:
  application:
    name: Notification Service
  profiles:
    active: dev

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: ${MONGO_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        max-concurrency: 10
        prefetch: 1
        concurrency: 3
        default-requeue-rejected: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  thymeleaf:
    check-template-location: false

# Interceptor related configurations
interceptor:
  mdc:
    trace:
      header: "X-Trace-Id"
      key: "traceId"

# API related
api:
  template:
    base_url: /api/v1/template

# Configure the channels for RabbitMQ listener
listener:
  factory:
    high:
      concurrentConsumers: 5
      maxConcurrentConsumers: 10
      preFetchCount: 1
    medium:
      concurrentConsumers: 2
      maxConcurrentConsumers: 5
      preFetchCount: 5
    low:
      concurrentConsumers: 1
      maxConcurrentConsumers: 2
      preFetchCount: 20

server:
  port: 6300